### ISSUE TITLE
WindowManagerGlobal.java line 491

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#10]
#### in android.view.WindowManagerGlobal.findViewLocked

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c45f54af8b88c296309f74d?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c45f54af8b88c296309f74d?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@7dd3658[] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:491)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:397)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
       at android.app.Dialog.dismissDialog(Dialog.java:418)
       at android.app.Dialog.dismiss(Dialog.java:401)
       at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:171)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:6747)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
