### ISSUE TITLE
Posix.java

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#13]
#### in libcore.io.Posix.writeBytes

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4619bef8b88c29630d6341?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4619bef8b88c29630d6341?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Caused by android.system.ErrnoException: write failed: ENOSPC (No space left on device)
       at libcore.io.Posix.writeBytes(Posix.java)
       at libcore.io.Posix.write(Posix.java:258)
       at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
       at libcore.io.IoBridge.write(IoBridge.java:497)
       at java.io.FileOutputStream.write(FileOutputStream.java:186)
       at com.androidnetworking.utils.Utils.saveFile(Utils.java:189)
       at com.androidnetworking.internal.InternalNetworking.performDownloadRequest(InternalNetworking.java:185)
       at com.androidnetworking.internal.InternalRunnable.executeDownloadRequest(InternalRunnable.java:102)
       at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:57)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:818)
```
