### ISSUE TITLE
RuntimeException: Unable to reach IQSService

### ISSUE THREAD

**Issue by firemaples** [firemaples/EverTranslator#130]
```
Fatal Exception: java.lang.RuntimeException: Unable to bind to service tw.firemaples.onscreenocr.QuickTileService@db139a3 with Intent { cmp=tw.firemaples.onscreenocr/.QuickTileService (has extras) }: java.lang.RuntimeException: Unable to reach IQSService
       at android.app.ActivityThread.handleBindService(ActivityThread.java:4270)
       at android.app.ActivityThread.access$300(ActivityThread.java:240)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2077)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:238)
       at android.app.ActivityThread.main(ActivityThread.java:7853)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
Caused by java.lang.RuntimeException: Unable to reach IQSService
       at android.service.quicksettings.TileService.onBind(TileService.java:360)
       at android.app.ActivityThread.handleBindService(ActivityThread.java:4255)
       at android.app.ActivityThread.access$300(ActivityThread.java:240)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2077)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:238)
       at android.app.ActivityThread.main(ActivityThread.java:7853)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
Caused by android.os.DeadObjectException
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:524)
       at android.service.quicksettings.IQSService$Stub$Proxy.getTile(IQSService.java:285)
       at android.service.quicksettings.TileService.onBind(TileService.java:358)
       at android.app.ActivityThread.handleBindService(ActivityThread.java:4255)
       at android.app.ActivityThread.access$300(ActivityThread.java:240)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2077)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:238)
       at android.app.ActivityThread.main(ActivityThread.java:7853)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
```

**Comment by firemaples** [comment]
https://gitlab.e.foundation/e/os/android_frameworks_base/commit/ee68fd889c2dfcd895b8e73fc39d7b97826dc3d8
