### ISSUE TITLE
Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0800ec

### ISSUE THREAD

**Issue by firemaples** [firemaples/EverTranslator#140]
https://console.firebase.google.com/u/1/project/ever-translator/crashlytics/app/android:tw.firemaples.onscreenocr/issues/05e22d5665ba191043589652484b6134?time=last-seven-days&sessionEventKey=5FC806F8025F000108D84734D57BAD7C_1480219701161444535

```
Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0800ec
       at android.content.res.Resources.getResourceName(Resources.java:2070)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2441)
       at android.content.res.Resources.loadDrawable(Resources.java:2381)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
       at android.widget.ImageView.<init>(ImageView.java:146)
       at android.widget.ImageButton.<init>(ImageButton.java:86)
       at android.widget.ImageButton.<init>(ImageButton.java:82)
       at android.widget.ImageButton.<init>(ImageButton.java:78)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at tw.firemaples.onscreenocr.floatingviews.FloatingView.<init>(FloatingView.java)
       at tw.firemaples.onscreenocr.floatingviews.MovableFloatingView.<init>(MovableFloatingView.java)
       at tw.firemaples.onscreenocr.floatingviews.screencrop.MainBar.<init>(MainBar.java)
       at tw.firemaples.onscreenocr.ScreenTranslatorService._startFloatingView(ScreenTranslatorService.java)
       at tw.firemaples.onscreenocr.ScreenTranslatorService.onCreate(ScreenTranslatorService.java)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2785)
       at android.app.ActivityThread.access$1800(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5314)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:374)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by firemaples** [comment]
Trying to use drawable-v17 as a default drawable folder to it.

Reference: https://stackoverflow.com/a/59304459/2906153
