### ISSUE TITLE
YandexApiTranslator.kt line 56

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#21]
#### in tw.firemaples.onscreenocr.translate.YandexApiTranslator$translate$1$1.onError

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4a25d3f8b88c296367f997?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4a25d3f8b88c296367f997?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Non-fatal Exception: java.lang.Exception: Call Yandex translation API failed
       at tw.firemaples.onscreenocr.translate.YandexApiTranslator$translate$1$1.onError(YandexApiTranslator.kt:56)
       at com.androidnetworking.common.ANRequest.deliverErrorResponse(ANRequest.java:737)
       at com.androidnetworking.common.ANRequest.deliverError(ANRequest.java:663)
       at com.androidnetworking.internal.InternalRunnable$1.run(InternalRunnable.java:159)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

Caused by com.androidnetworking.error.ANError
       at com.androidnetworking.internal.InternalRunnable.executeSimpleRequest(InternalRunnable.java:80)
       at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:54)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:784)
```

**Comment by firemaples** [comment]
No reason?
