### ISSUE TITLE
RealBufferedSource.java line 215

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#22]
#### in okio.RealBufferedSource.readUtf8LineStrict

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4a7582f8b88c29636dedf3?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4a7582f8b88c29636dedf3?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Non-fatal Exception: java.lang.Exception: Call Yandex translation API failed
       at tw.firemaples.onscreenocr.translate.YandexApiTranslator$translate$1$1.onError(YandexApiTranslator.kt:56)
       at com.androidnetworking.common.ANRequest.deliverErrorResponse(ANRequest.java:737)
       at com.androidnetworking.common.ANRequest.deliverError(ANRequest.java:663)
       at com.androidnetworking.internal.InternalRunnable$1.run(InternalRunnable.java:159)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Caused by java.io.IOException: unexpected end of stream on Connection{translate.yandex.net:443, proxy=DIRECT hostAddress=translate.yandex.net/213.180.204.194:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 protocol=http/1.1}
       at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:205)
       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:56)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at okhttp3.RealCall.execute(RealCall.java:63)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(Unknown Source:5)
       at com.androidnetworking.internal.InternalNetworking.performSimpleRequest(InternalNetworking.java:112)
       at com.androidnetworking.internal.InternalRunnable.executeSimpleRequest(InternalRunnable.java:68)
       at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:54)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.io.EOFException: \n not found: size=0 content=…
       at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215)
       at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:56)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at okhttp3.RealCall.execute(RealCall.java:63)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(Unknown Source:5)
       at com.androidnetworking.internal.InternalNetworking.performSimpleRequest(InternalNetworking.java:112)
       at com.androidnetworking.internal.InternalRunnable.executeSimpleRequest(InternalRunnable.java:68)
       at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:54)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:764)
```
