### ISSUE TITLE
FloatingView.java line 152

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#24]
#### in tw.firemaples.onscreenocr.floatingviews.FloatingView.attachToWindow

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4b8d7cf8b88c296387ff2e?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4b8d7cf8b88c296387ff2e?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Fatal Exception: java.lang.RuntimeException: InputChannel is not initialized.
       at android.view.InputEventReceiver.nativeInit(InputEventReceiver.java)
       at android.view.InputEventReceiver.<init>(InputEventReceiver.java:78)
       at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:7964)
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:979)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:372)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:129)
       at tw.firemaples.onscreenocr.floatingviews.FloatingView.attachToWindow(FloatingView.java:152)
       at tw.firemaples.onscreenocr.floatingviews.screencrop.DrawAreaView.attachToWindow(DrawAreaView.kt:34)
       at tw.firemaples.onscreenocr.floatingviews.screencrop.MainBar$1.startSelection(MainBar.kt:288)
       at tw.firemaples.onscreenocr.StateManager$dispatchStartSelection$1.invoke(StateManager.kt:104)
       at tw.firemaples.onscreenocr.StateManager$dispatchStartSelection$1.invoke(StateManager.kt:21)
       at tw.firemaples.onscreenocr.StateManager$dispatch$1.invokeSuspend(StateManager.kt:168)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
       at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:146)
       at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:13)
       at android.os.Handler.handleCallback(Handler.java:891)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Comment by firemaples** [comment]
It's a known issue crossed versions on Google's issue tracker and not fixable now.

https://stackoverflow.com/questions/34039657/what-might-be-the-reason-for-this-exception-java-lang-runtimeexception-inputch/35311335
https://issuetracker.google.com/u/1/issues/37018931
