### ISSUE TITLE
???

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#25]
#### in com.excelliance.kxqp.platform.f.d.c.a

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4bf0b0f8b88c29638f38b1?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4bf0b0f8b88c29638f38b1?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
# Crashlytics - plaintext stacktrace downloaded by firemaples at Wed, 13 Feb 2019 07:10:28 GMT
# URL: https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4bf0b0f8b88c29638f38b1/sessions/latest
# Organization: Firemaples’
# Platform: android
# Application: Ever Translator
# Version: 2.3.3 (61)
# Bundle Identifier: tw.firemaples.onscreenocr
# Issue #: 306
# Issue ID: 5c4bf0b0f8b88c29638f38b1
# Session ID: 5C4BEC7903D7000150C8CACF3CD33CEB_DNE_0_v2
# Date: 2019-01-26T05:21:00Z
# OS Version: 8.1.0
# Device: SKR-A0
# RAM Free: 26.8%
# Disk Free: 9.1%

Key | Value
-- | --
CountryCode | CN
DeviceLanguage | zh
DisplayCountry | 中国
DisplayLanguage | 中文
isPlayServiceAvailable | true
OCR_Lang_Code | jpn
OCR_Page_Seg_Mode | Auto
OCR_Site | github
OCR_Site_Url | https://github.com/firemaples/tessdata/raw/master/%s
Package_name | tw.firemaples.onscreenocr
PlayServiceVersionCode | 14366019
PlayServiceVersionName | 14.3.66 (040400-213742215)
Signature_SHA | gK7G8ZtYKeXYMsWzOZ0wP+rTP50=
Signature_SHA_is_correct | true
Tran_Lang_Code | zh



```
Non-fatal Exception: java.lang.IllegalStateException: Google translate not found or version is too old: null
       at tw.firemaples.onscreenocr.log.FirebaseEvent.logShowGoogleTranslateWindowFailed(FirebaseEvent.kt:193)
       at tw.firemaples.onscreenocr.translate.GoogleTranslateUtil$Companion.start(GoogleTranslateUtil.kt:95)
       at tw.firemaples.onscreenocr.views.OCRResultWindow.openGoogleTranslateApp(OCRResultWindow.kt:252)
       at tw.firemaples.onscreenocr.views.OCRResultWindow.access$openGoogleTranslateApp(OCRResultWindow.kt:30)
       at tw.firemaples.onscreenocr.views.OCRResultWindow$onClickListener$1.onClick(OCRResultWindow.kt:92)
       at android.view.View.performClick(View.java:6302)
       at android.view.View$PerformClick.run(View.java:24795)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6530)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:444)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:812)

Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PROCESS_TEXT typ=text/plain flg=0x10000000 pkg=com.google.android.apps.translate (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1947)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.excelliance.kxqp.platform.f.d.c.a(Unknown Source:57)
       at com.excelliance.kxqp.platform.c.b.e.sm.a(Unknown Source)
       at com.excelliance.kxqp.platform.c.b.e.sm.execStartActivity(Unknown Source)
       at android.app.ContextImpl.startActivity(ContextImpl.java:927)
       at android.app.ContextImpl.startActivity(ContextImpl.java:886)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:372)
       at tw.firemaples.onscreenocr.translate.GoogleTranslateUtil$Companion.start(GoogleTranslateUtil.kt:66)
       at tw.firemaples.onscreenocr.views.OCRResultWindow.openGoogleTranslateApp(OCRResultWindow.kt:252)
       at tw.firemaples.onscreenocr.views.OCRResultWindow.access$openGoogleTranslateApp(OCRResultWindow.kt:30)
       at tw.firemaples.onscreenocr.views.OCRResultWindow$onClickListener$1.onClick(OCRResultWindow.kt:92)
       at android.view.View.performClick(View.java:6302)
       at android.view.View$PerformClick.run(View.java:24795)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6530)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:444)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:812)
```
