### ISSUE TITLE
Doesn't work, java error

### ISSUE THREAD

**Issue by RikCost** [firemaples/EverTranslator#267]
Boot, first translate- ok, all work, 
![Screenshot_2023-03-11-01-55-34-797_snoddasmannen galimulator](https://user-images.githubusercontent.com/69048938/224443663-1c08908a-9ab7-42b8-a989-ff803fc14626.jpg)
second translate- error.

**Comment by uomar8** [comment]
Could you give more information like what android version you use and what's your device?

**Comment by RikCost** [comment]
Android 12 SKQ1.211006.001, device POCO X3 Pro, if its important MIUI Global 13.0.2 stable

**Comment by firemaples** [comment]
Looks like the same issue with #194, let me check if there's a new solution or not.

**Comment by RikCost** [comment]
Still not working

**Comment by uomar8** [comment]
> Still not working

It's better if you could use android studio and give us the logcat it's very easy to do that

Unfortunately the error is so general it's not easy to know what code made this error but if you could use android studio we could know what class and what really made this error 

[View logs with Logcat](https://developer.android.com/studio/debug/logcat#:~:text=line%20of%20code.-,Get%20started%20with%20the%20Logcat%20window,Logcat%20from%20the%20menu%20bar.)

**Comment by RikCost** [comment]
Maybe this?

Error inserting flex_time=3522000 job_id=-1 period=7045000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=233414000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1694890319509 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 [CONTEXT service_id=218 ]
                                                                                                    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
                                                                                                    	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                                                    	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:940)
                                                                                                    	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
                                                                                                    	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1702)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1597)
                                                                                                    	at chhl.f(:com.google.android.gms@233414044@23.34.14 (190400-560151436):721)
                                                                                                    	at chgf.n(:com.google.android.gms@233414044@23.34.14 (190400-560151436):29)
                                                                                                    	at chgf.u(:com.google.android.gms@233414044@23.34.14 (190400-560151436):225)
                                                                                                    	at chgf.h(:com.google.android.gms@233414044@23.34.14 (190400-560151436):54)
                                                                                                    	at chby.run(:com.google.android.gms@233414044@23.34.14 (190400-560151436):72)
                                                                                                    	at agxi.c(:com.google.android.gms@233414044@23.34.14 (190400-560151436):50)
                                                                                                    	at agxi.run(:com.google.android.gms@233414044@23.34.14 (190400-560151436):76)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at ahcq.run(:com.google.android.gms@233414044@23.34.14 (190400-560151436):8)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)


![image](https://github.com/firemaples/EverTranslator/assets/69048938/fbe863fc-fc05-4b8b-b202-977c34e12742)
![image](https://github.com/firemaples/EverTranslator/assets/69048938/be5b39bb-3c02-44b5-84cb-1f64f9ef4cc8)

**Comment by uomar8** [comment]
> Maybe this?
> 
> Error inserting flex_time=3455000 job_id=-1 period=6911000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=233414000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1694890386692 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 [CONTEXT service_id=218 ] android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE) at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:940) at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790) at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89) at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1702) at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1597) at chhl.f(:com.google.android.gms@233414044@23.34.14 (190400-560151436):721) at chgf.n(:com.google.android.gms@233414044@23.34.14 (190400-560151436):29) at chgf.u(:com.google.android.gms@233414044@23.34.14 (190400-560151436):225) at chgf.h(:com.google.android.gms@233414044@23.34.14 (190400-560151436):54) at chby.run(:com.google.android.gms@233414044@23.34.14 (190400-560151436):72) at agxi.c(:com.google.android.gms@233414044@23.34.14 (190400-560151436):50) at agxi.run(:com.google.android.gms@233414044@23.34.14 (190400-560151436):76) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) at ahcq.run(:com.google.android.gms@233414044@23.34.14 (190400-560151436):8) ![image](https://user-images.githubusercontent.com/69048938/268466083-fbe863fc-fc05-4b8b-b202-977c34e12742.png) ![image](https://user-images.githubusercontent.com/69048938/268466107-be5b39bb-3c02-44b5-84cb-1f64f9ef4cc8.png)

It's really good that you reached this point

Try to filter the logcat so it will only show EverTranslator

![Screenshot_20230917_040814](https://github.com/firemaples/EverTranslator/assets/7046347/20aa3fd7-482f-4e89-a086-a513298228b7)

**Comment by RikCost** [comment]
> > Maybe this?
> > Error inserting flex_time=3455000 job_id=-1 period=6911000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=233414000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1694890386692 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 [CONTEXT service_id=218 ] android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE) at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:940) at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790) at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89) at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1702) at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1597) at chhl.f(:com.google.android.gms@233414044@23.34.14 (190400-560151436):721) at chgf.n(:com.google.android.gms@233414044@23.34.14 (190400-560151436):29) at chgf.u(:com.google.android.gms@233414044@23.34.14 (190400-560151436):225) at chgf.h(:com.google.android.gms@233414044@23.34.14 (190400-560151436):54) at chby.run(:com.google.android.gms@233414044@23.34.14 (190400-560151436):72) at agxi.c(:com.google.android.gms@233414044@23.34.14 (190400-560151436):50) at agxi.run(:com.google.android.gms@233414044@23.34.14 (190400-560151436):76) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) at ahcq.run(:com.google.android.gms@233414044@23.34.14 (190400-560151436):8) ![image](https://user-images.githubusercontent.com/69048938/268466083-fbe863fc-fc05-4b8b-b202-977c34e12742.png) ![image](https://user-images.githubusercontent.com/69048938/268466107-be5b39bb-3c02-44b5-84cb-1f64f9ef4cc8.png)
> 
> It's really good that you reached this point
> 
> Try to filter the logcat so it will only show EverTranslator
> 
> ![Screenshot_20230917_040814](https://user-images.githubusercontent.com/7046347/268477512-20aa3fd7-482f-4e89-a086-a513298228b7.jpg)

If i try this filter, all just empty
![image](https://github.com/firemaples/EverTranslator/assets/69048938/c145b78a-7c3f-400a-a362-279c41b2db12)

**Comment by uomar8** [comment]
You can't get the debug from already built app you need to build it again

1- First download the source code from here
You could use git tools or (download as zip it's much easier)

2- you need to open the project using android studio

3- build the app and run the app from android studio
![deploy-run-app-new-ui_edit_319456996064796](https://github.com/firemaples/EverTranslator/assets/7046347/671f6131-a3a4-4052-bfcd-fbfc9ec78083)

**Comment by RikCost** [comment]
2023-09-17 14:38:38.497 27850-28027 ScreenExtractor         tw.firemaples.onscreenocr_debug      W  [DefaultDispatcher-worker-3]
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:2431)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2409)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2392)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2334)
                                                                                                    	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:235)
                                                                                                    	at android.media.projection.MediaProjection.<init>(MediaProjection.java:59)
                                                                                                    	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:119)
                                                                                                    	at tw.firemaples.onscreenocr.screenshot.ScreenExtractor$doCaptureScreen$2.invokeSuspend(ScreenExtractor.kt:113)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
                                                                                                    	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1187)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1146)
2023-09-17 14:38:38.499 27850-27850 FloatingStateManager    tw.firemaples.onscreenocr_debug      D  [main]
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:2431)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2409)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2392)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2334)
                                                                                                    	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:235)
                                                                                                    	at android.media.projection.MediaProjection.<init>(MediaProjection.java:59)
                                                                                                    	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:119)
                                                                                                    	at tw.firemaples.onscreenocr.screenshot.ScreenExtractor$doCaptureScreen$2.invokeSuspend(ScreenExtractor.kt:113)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
                                                                                                    	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1187)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1146)



![image](https://github.com/firemaples/EverTranslator/assets/69048938/4df85fad-ad01-4252-8ef9-bd00ea4fc9b5)
![image](https://github.com/firemaples/EverTranslator/assets/69048938/baaa8c05-5cc4-48a7-ae94-07a2676cb135)

**Comment by RikCost** [comment]
Add 5 internal lines:


[DefaultDispatcher-worker-3]
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:2431)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2409)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2392)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2334)
                                                                                                    	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:235)
                                                                                                    	at android.media.projection.MediaProjection.<init>(MediaProjection.java:59)
                                                                                                    	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:119)
                                                                                                    	at tw.firemaples.onscreenocr.screenshot.ScreenExtractor$doCaptureScreen$2.invokeSuspend(ScreenExtractor.kt:113)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
                                                                                                    	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1187)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1146)


![image](https://github.com/firemaples/EverTranslator/assets/69048938/ceb6ce56-9940-4f55-914f-29750f862806)

**Comment by RikCost** [comment]
![image](https://github.com/firemaples/EverTranslator/assets/69048938/b87a5f61-3b07-43a1-8766-0aea6db40416)

**Comment by uomar8** [comment]
Please keep android studio for a while

I will try some possible code changes and see if it's fix the problem
