### ISSUE TITLE
RemoteConfigUtil.kt line 29

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#27]
#### in tw.firemaples.onscreenocr.remoteconfig.RemoteConfigUtil$remoteConfig$2.invoke

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4ebe29f8b88c2963c6d4c8?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c4ebe29f8b88c2963c6d4c8?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Fatal Exception: java.lang.RuntimeException: Unable to create application tw.firemaples.onscreenocr.CoreApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process tw.firemaples.onscreenocr. Make sure to call FirebaseApp.initializeApp(Context) first.
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6499)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Caused by java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process tw.firemaples.onscreenocr. Make sure to call FirebaseApp.initializeApp(Context) first.
       at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.2:240)
       at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(Unknown Source:11)
       at tw.firemaples.onscreenocr.remoteconfig.RemoteConfigUtil$remoteConfig$2.invoke(RemoteConfigUtil.kt:29)
       at tw.firemaples.onscreenocr.remoteconfig.RemoteConfigUtil$remoteConfig$2.invoke(RemoteConfigUtil.kt:23)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at tw.firemaples.onscreenocr.remoteconfig.RemoteConfigUtil.getRemoteConfig(RemoteConfigUtil.kt)
       at tw.firemaples.onscreenocr.remoteconfig.RemoteConfigUtil.getString(RemoteConfigUtil.kt:62)
       at tw.firemaples.onscreenocr.remoteconfig.RemoteConfigUtil.getTrainedDataSites(RemoteConfigUtil.kt:83)
       at tw.firemaples.onscreenocr.ocr.OCRFileUtil.getTrainedDataSites(OCRFileUtil.kt:45)
       at tw.firemaples.onscreenocr.ocr.OCRFileUtil.getTrainedDataDownloadSite(OCRFileUtil.kt:42)
       at tw.firemaples.onscreenocr.log.UserInfoUtils.updateClientSettings(UserInfoUtils.kt:38)
       at tw.firemaples.onscreenocr.log.UserInfoUtils.setClientInfo(UserInfoUtils.kt:33)
       at tw.firemaples.onscreenocr.CoreApplication.onCreate(CoreApplication.kt:31)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6496)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
