### ISSUE TITLE
Linux.java

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#30]
#### in libcore.io.Linux.writeBytes

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c523fc0f8b88c296317f9d6?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c523fc0f8b88c296317f9d6?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Non-fatal Exception: com.androidnetworking.error.ANError: com.androidnetworking.error.ANError: java.io.IOException: write failed: ENOSPC (No space left on device)
       at com.androidnetworking.internal.InternalRunnable.executeDownloadRequest(InternalRunnable.java:114)
       at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:57)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:764)

Caused by android.system.ErrnoException: write failed: ENOSPC (No space left on device)
       at libcore.io.Linux.writeBytes(Linux.java)
       at libcore.io.Linux.write(Linux.java:288)
       at libcore.io.BlockGuardOs.write(BlockGuardOs.java:345)
       at libcore.io.IoBridge.write(IoBridge.java:553)
       at java.io.FileOutputStream.write(FileOutputStream.java:326)
       at com.androidnetworking.utils.Utils.saveFile(Utils.java:189)
       at com.androidnetworking.internal.InternalNetworking.performDownloadRequest(InternalNetworking.java:185)
       at com.androidnetworking.internal.InternalRunnable.executeDownloadRequest(InternalRunnable.java:102)
       at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:57)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by firemaples** [comment]
Disk no space when trying to call API
