### ISSUE TITLE
ContextImpl.java

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#35]
#### in android.app.ContextImpl.startServiceCommon

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c555032f8b88c2963600528?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c555032f8b88c2963600528?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Fatal Exception: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java)
       at android.app.ContextImpl.startService(ContextImpl.java)
       at android.content.ContextWrapper.startService(ContextWrapper.java)
       at com.google.firebase.iid.zzat.zze(Unknown Source:130)
       at com.google.firebase.iid.zzat.zzd(Unknown Source:91)
       at com.google.firebase.iid.zzat.zzc(Unknown Source:90)
       at com.google.firebase.iid.zzr.zza(Unknown Source:73)
       at com.google.firebase.iid.zzs.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
       at java.lang.Thread.run(Thread.java)
```
