### ISSUE TITLE
DialogView.java line 102

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#51]
#### in tw.firemaples.onscreenocr.floatingviews.screencrop.DialogView$1.onClick

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c6c8b45f8b88c29636ffc93?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c6c8b45f8b88c29636ffc93?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void tw.firemaples.onscreenocr.floatingviews.screencrop.DialogView$OnDialogViewCallback.onConfirmClick(tw.firemaples.onscreenocr.floatingviews.screencrop.DialogView)' on a null object reference
       at tw.firemaples.onscreenocr.floatingviews.screencrop.DialogView$1.onClick(DialogView.java:102)
       at android.view.View.performClick(View.java:6259)
       at android.view.View$PerformClick.run(View.java:24732)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6673)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```
