### ISSUE TITLE
DialogView.java line 104

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#52]
#### in tw.firemaples.onscreenocr.floatingviews.screencrop.DialogView$1.onClick

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c6cbcb6f8b88c2963736be9?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c6cbcb6f8b88c2963736be9?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void tw.firemaples.onscreenocr.floatingviews.screencrop.DialogView$OnDialogViewCallback.onCancelClicked(tw.firemaples.onscreenocr.floatingviews.screencrop.DialogView)' on a null object reference
       at tw.firemaples.onscreenocr.floatingviews.screencrop.DialogView$1.onClick(DialogView.java:104)
       at android.view.View.performClick(View.java:6652)
       at android.view.View.performClickInternal(View.java:6624)
       at android.view.View.access$3100(View.java:787)
       at android.view.View$PerformClick.run(View.java:26213)
       at android.os.Handler.handleCallback(Handler.java:891)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```
