### ISSUE TITLE
InternalRunnable.java line 108

### ISSUE THREAD

**Issue by BotForHook** [firemaples/EverTranslator#9]
#### in com.androidnetworking.internal.InternalRunnable.executeDownloadRequest

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c45dbb1f8b88c29630736bc?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/firemaples/android/apps/tw.firemaples.onscreenocr/issues/5c45dbb1f8b88c29630736bc?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by firemaples** [comment]
```
Non-fatal Exception: com.androidnetworking.error.ANError
       at com.androidnetworking.internal.InternalRunnable.executeDownloadRequest(InternalRunnable.java:108)
       at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:57)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:818)
```
